version: '3.8'

services:
  talks:
    image: talks:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: slidev-talks
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - slidev-network
    # The nginx.conf will be copied during the build process in the Dockerfile
    # No need to mount it as a volume
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
      labels:
        - "com.github.repo=https://github.com/Sjoerd-Bo3/talks-example.git"
        - "com.slidev.version=${SLIDEV_VERSION:-latest}"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 86400 --cleanup
    environment:
      - TZ=Europe/Amsterdam
    networks:
      - slidev-network

networks:
  slidev-network:
    driver: bridge
